"""Windshield — reusable Playwright browser automation utilities."""

from windshield._errors import WindshieldError
from windshield.adapters import (
    DEFAULT_ROTATION_ORDER,
    BackendType,
    LocatorAdapter,
    PageAdapter,
    UnsupportedOperationError,
    create_page,
)
from windshield.browser import (
    chrome_executable_from_dir,
    discover_chrome_binary,
    download_chrome_for_testing,
    download_url_to_file,
    ensure_chrome_runtime_permissions,
    extract_zip_with_permissions,
    fetch_cdp_version,
    fetch_json_url,
    find_existing_cft_executable,
    resolve_cft_download_url,
    wait_for_cdp_version,
)
from windshield.challenge import (
    extract_reference_code_from_page,
    extract_reference_code_from_text,
    is_challenge_page,
    wait_for_challenge_to_clear,
)
from windshield.debug import (
    append_debug_jsonl,
    capture_page_snapshot,
    install_page_runtime_debug_capture,
    normalize_runtime_capture_text,
    snapshot_safe_name,
    write_text,
)
from windshield.http import (
    build_http_opener,
    describe_browser_location,
    match_browser_route,
    sanitize_error_text,
    sanitize_manual_guidance_text,
    url_contains_any_fragment,
)
from windshield.overlay import (
    describe_manual_page_guidance,
    wait_for_manual_continue,
    wait_for_manual_otp_continue,
)
from windshield.page import (
    click_control_with_labels,
    click_first_selector_best_effort,
    click_first_visible,
    click_optional_selectors,
    click_selector_any,
    fill_first_visible,
    first_visible_selector_match,
    has_any_selector,
    is_page_or_context_closed_error,
    iter_locator_contexts,
    iter_page_frames,
    matching_text_snippets,
    page_contains_any_text,
    press_enter_first_visible,
    read_first_visible_input_value,
    read_page_text,
    retry_browser_wait,
    script_set_first_visible_value,
    set_first_visible_value_robust,
    submit_first_matching_form,
    title_contains_any_text,
    type_first_visible,
    wait_for_any_selector,
    wait_for_any_selector_in_contexts,
    wait_for_selector_to_disappear,
    wait_for_text_to_disappear,
    wait_for_url_contains,
)
from windshield.rotation import RotationStrategy
from windshield.stealth import (
    DEFAULT_STEALTH_USER_AGENTS,
    normalize_selector_list,
    normalize_string_list,
    resolve_rotating_user_agent,
)

__all__ = [
    "WindshieldError",
    # adapters
    "BackendType",
    "DEFAULT_ROTATION_ORDER",
    "LocatorAdapter",
    "PageAdapter",
    "UnsupportedOperationError",
    "create_page",
    # rotation
    "RotationStrategy",
    # browser
    "chrome_executable_from_dir",
    "discover_chrome_binary",
    "download_chrome_for_testing",
    "download_url_to_file",
    "ensure_chrome_runtime_permissions",
    "extract_zip_with_permissions",
    "fetch_cdp_version",
    "fetch_json_url",
    "find_existing_cft_executable",
    "resolve_cft_download_url",
    "wait_for_cdp_version",
    # challenge
    "extract_reference_code_from_page",
    "extract_reference_code_from_text",
    "is_challenge_page",
    "wait_for_challenge_to_clear",
    # debug
    "append_debug_jsonl",
    "capture_page_snapshot",
    "install_page_runtime_debug_capture",
    "normalize_runtime_capture_text",
    "snapshot_safe_name",
    "write_text",
    # http
    "build_http_opener",
    "describe_browser_location",
    "match_browser_route",
    "sanitize_error_text",
    "sanitize_manual_guidance_text",
    "url_contains_any_fragment",
    # overlay
    "describe_manual_page_guidance",
    "wait_for_manual_continue",
    "wait_for_manual_otp_continue",
    # page
    "click_control_with_labels",
    "click_first_selector_best_effort",
    "click_first_visible",
    "click_optional_selectors",
    "click_selector_any",
    "fill_first_visible",
    "first_visible_selector_match",
    "has_any_selector",
    "is_page_or_context_closed_error",
    "iter_locator_contexts",
    "iter_page_frames",
    "matching_text_snippets",
    "page_contains_any_text",
    "press_enter_first_visible",
    "read_first_visible_input_value",
    "read_page_text",
    "retry_browser_wait",
    "script_set_first_visible_value",
    "set_first_visible_value_robust",
    "submit_first_matching_form",
    "title_contains_any_text",
    "type_first_visible",
    "wait_for_any_selector",
    "wait_for_any_selector_in_contexts",
    "wait_for_selector_to_disappear",
    "wait_for_text_to_disappear",
    "wait_for_url_contains",
    # stealth
    "DEFAULT_STEALTH_USER_AGENTS",
    "normalize_selector_list",
    "normalize_string_list",
    "resolve_rotating_user_agent",
]
